app = "bybit-proxy"

[build]
  image = "python:3.10"

[env]
  FLASK_ENV = "production"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
